"""
Documentation Generator - Generates comprehensive documentation
"""
from pathlib import Path
from typing import Dict, Any
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class DocumentationGenerator:
    """Generates documentation for code modernization"""
    
    def __init__(self, analysis_result: Dict[str, Any], output_path: Path):
        """
        Initialize documentation generator
        
        Args:
            analysis_result: Result from CodeAnalyzer
            output_path: Path to output directory
        """
        self.analysis = analysis_result
        self.output_path = Path(output_path)
        self.docs_path = self.output_path / "docs"
        self.docs_path.mkdir(exist_ok=True)
    
    def generate(self):
        """Generate all documentation files"""
        logger.info("Generating documentation...")
        
        # Generate main documentation files
        self._generate_legacy_analysis()
        self._generate_modernization_plan()
        self._generate_summary()
        self._generate_code_mapping()
    
    def _generate_legacy_analysis(self):
        """Generate legacy code analysis document"""
        content = f"""# Legacy Code Analysis

## Executive Summary

This document provides a comprehensive analysis of the legacy codebase extracted from:
**Source Path**: `{self.analysis['source_path']}`

**Analysis Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Codebase Overview

- **Total Files**: {self.analysis['summary']['total_files']}
- **Languages**: {', '.join(self.analysis['summary']['languages'])}
- **Frameworks**: {', '.join(self.analysis['summary']['frameworks']) if self.analysis['summary']['frameworks'] else 'None detected'}

## File Structure

### Source Files

"""
        for file_info in self.analysis['files'][:20]:  # Limit for readability
            content += f"- `{file_info['path']}` ({file_info['lines']} lines)\n"
        
        content += f"""
## Architecture Analysis

### Detected Patterns

{self._format_dict(self.analysis.get('patterns', {}))}

### Business Logic Components

- **Services**: {len(self.analysis['business_logic'].get('services', []))} files
- **Controllers**: {len(self.analysis['business_logic'].get('controllers', []))} files
- **Models**: {len(self.analysis['business_logic'].get('models', []))} files
- **Repositories**: {len(self.analysis['business_logic'].get('repositories', []))} files

## Dependencies

### Maven Dependencies
{len(self.analysis['dependencies'].get('maven', []))} dependencies found

### NPM Dependencies
{len(self.analysis['dependencies'].get('npm', []))} dependencies found

### Python Dependencies
{len(self.analysis['dependencies'].get('pip', []))} dependencies found

## API Endpoints

{len(self.analysis['structure'].get('endpoints', []))} endpoints detected

## Recommendations

1. **Modernization Target**: Python with FastAPI recommended
2. **Test Coverage**: Target 80%+ coverage
3. **Documentation**: Auto-generate API documentation
4. **Type Safety**: Add type hints throughout

---
*Generated by Code Modernization Tool*
"""
        
        file_path = self.docs_path / "LEGACY_CODE_ANALYSIS.md"
        file_path.write_text(content)
        logger.info(f"Generated: {file_path}")
    
    def _generate_modernization_plan(self):
        """Generate modernization plan document"""
        content = f"""# Modernization Plan

## Overview

This document outlines the plan for modernizing the legacy codebase.

## Source Analysis

- **Source Path**: `{self.analysis['source_path']}`
- **Total Files**: {self.analysis['summary']['total_files']}
- **Primary Language**: {self.analysis['summary']['languages'][0] if self.analysis['summary']['languages'] else 'Unknown'}

## Modernization Strategy

### Target Stack

- **Language**: Python 3.11+
- **Framework**: FastAPI
- **ORM**: SQLAlchemy 2.0+
- **Testing**: pytest with 80%+ coverage
- **Documentation**: Auto-generated OpenAPI/Swagger

### Conversion Mapping

| Legacy Component | Modern Component | Status |
|-----------------|------------------|--------|
| Spring Boot | FastAPI | To Convert |
| JPA | SQLAlchemy | To Convert |
| Maven | pip/requirements.txt | To Convert |

## Implementation Phases

1. **Analysis** ✅ - Complete
2. **Documentation** ✅ - Complete
3. **Code Conversion** - In Progress
4. **Test Generation** - Pending
5. **Validation** - Pending

## Success Criteria

- ✅ 100% feature parity
- ✅ 80%+ test coverage
- ✅ All tests passing
- ✅ API documentation generated

---
*Generated by Code Modernization Tool*
"""
        
        file_path = self.docs_path / "MODERNIZATION_PLAN.md"
        file_path.write_text(content)
        logger.info(f"Generated: {file_path}")
    
    def _generate_summary(self):
        """Generate summary document"""
        content = f"""# Code Modernization Summary

## Project Status

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Statistics

- **Source Files Analyzed**: {self.analysis['summary']['total_files']}
- **Languages Detected**: {len(self.analysis['summary']['languages'])}
- **Frameworks Detected**: {len(self.analysis['summary']['frameworks'])}

## Components

- **Services**: {len(self.analysis['business_logic'].get('services', []))}
- **Controllers**: {len(self.analysis['business_logic'].get('controllers', []))}
- **Models**: {len(self.analysis['business_logic'].get('models', []))}
- **Repositories**: {len(self.analysis['business_logic'].get('repositories', []))}

## Next Steps

1. Review generated documentation
2. Execute code conversion
3. Generate test suite
4. Validate modernization

---
*Generated by Code Modernization Tool*
"""
        
        file_path = self.docs_path / "MODERNIZATION_SUMMARY.md"
        file_path.write_text(content)
        logger.info(f"Generated: {file_path}")
    
    def _generate_code_mapping(self):
        """Generate code mapping document"""
        content = """# Code Mapping Reference

## File Mapping

This document maps legacy code files to their modernized equivalents.

| Legacy File | Modern File | Notes |
|------------|------------|-------|
| (To be generated during conversion) | | |

## Component Mapping

| Legacy Component | Modern Component |
|-----------------|------------------|
| @RestController | FastAPI Router |
| @Service | Python Service Class |
| @Repository | SQLAlchemy Repository |
| @Entity | SQLAlchemy Model |
| Bean Validation | Pydantic Models |

---
*Generated by Code Modernization Tool*
"""
        
        file_path = self.docs_path / "CODE_MAPPING.md"
        file_path.write_text(content)
        logger.info(f"Generated: {file_path}")
    
    def _format_dict(self, data: Dict) -> str:
        """Format dictionary for markdown"""
        if not data:
            return "None"
        lines = []
        for key, value in data.items():
            if isinstance(value, (list, dict)):
                lines.append(f"- **{key}**: {len(value) if isinstance(value, list) else 'Dict'}")
            else:
                lines.append(f"- **{key}**: {value}")
        return "\n".join(lines)

