"""
Azure OpenAI Embedding Service
"""
import os
import logging
from typing import List, Dict, Any
import openai
from azure.identity import DefaultAzureCredential
import time

logger = logging.getLogger(__name__)

class AzureOpenAIEmbeddings:
    """Azure OpenAI embedding service for generating vector embeddings"""
    
    def __init__(self, 
                 endpoint: str = None,
                 api_key: str = None,
                 api_version: str = "2024-02-15-preview",
                 deployment_name: str = "text-embedding-ada-002"):
        """
        Initialize Azure OpenAI client
        
        Args:
            endpoint: Azure OpenAI endpoint URL
            api_key: Azure OpenAI API key
            api_version: API version to use
            deployment_name: Deployment name for embeddings
        """
        self.endpoint = endpoint or os.getenv('AZURE_OPENAI_ENDPOINT')
        self.api_key = api_key or os.getenv('AZURE_OPENAI_API_KEY')
        self.api_version = api_version or os.getenv('AZURE_OPENAI_API_VERSION', '2024-02-15-preview')
        self.deployment_name = deployment_name or os.getenv('AZURE_EMBEDDING_DEPLOYMENT_NAME', 'text-embedding-ada-002')
        
        if not self.endpoint:
            raise ValueError("Azure OpenAI endpoint is required")
        
        # Initialize OpenAI client
        self.client = openai.AzureOpenAI(
            azure_endpoint=self.endpoint,
            api_key=self.api_key,
            api_version=self.api_version
        )
        
        logger.info(f"Azure OpenAI client initialized with endpoint: {self.endpoint}")
        logger.info(f"Using deployment: {self.deployment_name}")
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text
        
        Args:
            text: Text to embed
            
        Returns:
            List[float]: Embedding vector
        """
        try:
            response = self.client.embeddings.create(
                model=self.deployment_name,
                input=text
            )
            return response.data[0].embedding
        except Exception as e:
            logger.error(f"Failed to generate embedding: {e}")
            raise
    
    def generate_embeddings_batch(self, texts: List[str], batch_size: int = 100) -> List[List[float]]:
        """
        Generate embeddings for multiple texts in batches
        
        Args:
            texts: List of texts to embed
            batch_size: Number of texts to process in each batch
            
        Returns:
            List[List[float]]: List of embedding vectors
        """
        all_embeddings = []
        
        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i:i + batch_size]
            
            try:
                response = self.client.embeddings.create(
                    model=self.deployment_name,
                    input=batch_texts
                )
                
                batch_embeddings = [data.embedding for data in response.data]
                all_embeddings.extend(batch_embeddings)
                
                logger.info(f"Generated embeddings for batch {i//batch_size + 1}/{(len(texts)-1)//batch_size + 1}")
                
                # Rate limiting - Azure OpenAI has rate limits
                if i + batch_size < len(texts):
                    time.sleep(0.1)  # Small delay between batches
                    
            except Exception as e:
                logger.error(f"Failed to generate embeddings for batch {i//batch_size + 1}: {e}")
                # Try individual embeddings for this batch
                for text in batch_texts:
                    try:
                        embedding = self.generate_embedding(text)
                        all_embeddings.append(embedding)
                    except Exception as individual_error:
                        logger.error(f"Failed to generate embedding for individual text: {individual_error}")
                        # Add zero vector as fallback
                        all_embeddings.append([0.0] * 1536)  # text-embedding-ada-002 has 1536 dimensions
        
        return all_embeddings
    
    def get_embedding_dimension(self) -> int:
        """Get the dimension of embeddings generated by this model"""
        # text-embedding-ada-002 has 1536 dimensions
        return 1536
    
    def test_connection(self) -> bool:
        """Test the connection to Azure OpenAI"""
        try:
            test_embedding = self.generate_embedding("test")
            logger.info("Azure OpenAI connection test successful")
            return True
        except Exception as e:
            logger.error(f"Azure OpenAI connection test failed: {e}")
            return False

class HybridEmbeddingService:
    """Hybrid embedding service that can use either sentence-transformers or Azure OpenAI"""
    
    def __init__(self, use_azure: bool = False, **kwargs):
        """
        Initialize hybrid embedding service
        
        Args:
            use_azure: Whether to use Azure OpenAI or sentence-transformers
            **kwargs: Additional arguments for the embedding service
        """
        self.use_azure = use_azure
        
        if use_azure:
            self.azure_service = AzureOpenAIEmbeddings(**kwargs)
            self.sentence_transformer = None
            self.embedding_dimension = self.azure_service.get_embedding_dimension()
        else:
            from sentence_transformers import SentenceTransformer
            model_name = kwargs.get('model_name', 'all-MiniLM-L6-v2')
            self.sentence_transformer = SentenceTransformer(model_name)
            self.azure_service = None
            self.embedding_dimension = 384  # all-MiniLM-L6-v2 dimension
    
    def generate_embedding(self, text: str) -> List[float]:
        """Generate embedding for a single text"""
        if self.use_azure:
            return self.azure_service.generate_embedding(text)
        else:
            embedding = self.sentence_transformer.encode(text)
            return embedding.tolist()
    
    def generate_embeddings_batch(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for multiple texts"""
        if self.use_azure:
            return self.azure_service.generate_embeddings_batch(texts)
        else:
            embeddings = self.sentence_transformer.encode(texts)
            return [embedding.tolist() for embedding in embeddings]
    
    def get_embedding_dimension(self) -> int:
        """Get the dimension of embeddings"""
        return self.embedding_dimension
    
    def test_connection(self) -> bool:
        """Test the connection"""
        if self.use_azure:
            return self.azure_service.test_connection()
        else:
            try:
                test_embedding = self.generate_embedding("test")
                return True
            except Exception as e:
                logger.error(f"Sentence transformer test failed: {e}")
                return False
